workflows:
  ios_build:
    name: Build iOS NativeScript App
    max_build_duration: 60
    environment:
      node: 16.15.0  # تأكد من تحديد الإصدار المناسب من Node.js
    scripts:
      - name: Install NativeScript CLI
        script: npm install -g nativescript
      - name: Install project dependencies
        script: npm install
      - name: Build NativeScript app for iOS
        script: tns build ios --bundle
    artifacts:
      - build/ios
    publishing:
      email:
        recipients:
          - ahmhll09@gamil.com  # ضع بريدك الإلكتروني لتلقي الإشعارات
